using Microsoft.EntityFrameworkCore;
using todolistApiv2.Models;

namespace todolistApiv2.Data
{
    public class DataContext : DbContext // Inherit from DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) 
            : base(options)
        {
        }
        public DbSet<User> Users { get; set; }
        public DbSet<Todo> Todos { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(u => u.UserId)
                .ValueGeneratedOnAdd(); // Configure Id to be autogenerated on add 1
            modelBuilder.Entity<Todo>()
                .Property(t => t.TodoId)
                .ValueGeneratedOnAdd(); // Configure Id to be autogenerated on add

            base.OnModelCreating(modelBuilder);
        }
    }
}
